export enum Service {
  // Preventive care
  PREVENTIVE_ROUTINE_WELL_EXAM = '[Preventive] Routine physical exam, well-child exam, or well-woman exam',
  PREVENTIVE_COLORECTAL_SCREENING = '[Preventive] Colorectal cancer screening or colonoscopy',
  PREVENTIVE_IMMUNIZATIONS = '[Preventive] Immunizations (ACA recommended)',
  PREVENTIVE_LAB_OUTPATIENT = '[Preventive] Laboratory services - outpatient',
  PREVENTIVE_MAMMOGRAM = '[Preventive] Mammogram',
  PREVENTIVE_MATERNITY_PHYSICIAN = '[Preventive] Maternity - Physician',
  PREVENTIVE_OSTEOPOROSIS_SCREENING = '[Preventive] Osteoporosis screening',
  PREVENTIVE_OTHER = '[Preventive] Other preventive services',

  // Medical care
  ACUPUNCTURE = 'Acupuncture (up to 12 visits per year)',
  ALLERGY_TESTING = 'Allergy testing',
  AMBULANCE = 'Ambulance',
  ANESTHESIA = 'Anesthesia',
  APPLIED_BEHAVIOR_ANALYSIS = 'Applied behavior analysis therapy',
  AUDIOLOGY_EXAM_PCP = 'Audiology exam - PCP',
  AUDIOLOGY_EXAM_SPECIALIST = 'Audiology exam - specialist',
  BEHAVIORAL_HEALTH_OUTPATIENT = 'Behavioral health and substance use disorder - outpatient',
  BEHAVIORAL_HEALTH_INPATIENT = 'Behavioral health and substance use disorder - acute inpatient, residential, partial hospital, intensive outpatient, and outpatient testing',
  CARDIAC_REHABILITATION = 'Cardiac rehabilitation',
  CHEMOTHERAPY = 'Chemotherapy - provider administered',
  CHIROPRACTIC_THERAPY = 'Chiropractic therapy (up to 25 visits per year)',
  COLORECTAL_DIAGNOSTIC = 'Colorectal cancer screening or colonoscopy - diagnostic',
  DIABETES = 'Diabetes - education, glucometers, insulin pumps',
  DIALYSIS = 'Dialysis',
  DURABLE_MEDICAL_EQUIPMENT = 'Durable medical equipment',
  EMERGENCY_ROOM = 'Emergency room services',
  EMERGENCY_ROOM_PHYSICIAN = 'Emergency room - physician',
  EYE_EXAM = 'Eye exam (one routine exam per year; as needed for medical conditions)',
  EYEWEAR = 'Eyewear (glasses or contact lenses needed due to eye surgery or for keratoconus)',
  GENETIC_COUNSELING_PCP = 'Genetic counseling - PCP',
  GENETIC_COUNSELING_SPECIALIST = 'Genetic counseling - specialist',
  GENETIC_TESTING = 'Genetic testing',
  HEARING_AIDS = 'Hearing aids (up to $1,200 per ear once every three years)',
  HEARING_EXAM_PCP = 'Hearing exam - PCP',
  HEARING_EXAM_SPECIALIST = 'Hearing exam - specialist',
  HEARING_TESTING = 'Hearing testing (audiometry)',
  HOME_HEALTH = 'Home health',
  HOSPICE = 'Hospice',
  HOSPITAL_INPATIENT = 'Hospital - inpatient',
  IMAGING_FACILITY = 'Imaging services - facility',
  IMAGING_PROFESSIONAL = 'Imaging services - professional',
  INFERTILITY_SERVICES = 'Infertility services',
  INJECTIONS_IV_THERAPY = 'Injections and IV therapy',
  LAB_INPATIENT = 'Laboratory services - inpatient',
  LIFESTYLE_SCREENING = 'Lifestyle screening (up to $100 per screening once every three years for employee and spouse)',
  MAMMOGRAM_DIAGNOSTIC = 'Mammogram - diagnostic',
  MATERNITY_INPATIENT = 'Maternity - inpatient',
  MEDICAL_SUPPLIES = 'Medical supplies',
  NUTRITIONAL_EDUCATION = 'Nutritional education',
  OBESITY_SURGERY = 'Obesity surgery (one procedure per lifetime)',
  OCCUPATIONAL_THERAPY_OUTPATIENT = 'Occupational therapy - outpatient',
  OCCUPATIONAL_THERAPY_INPATIENT = 'Occupational therapy - inpatient',
  OFFICE_VISIT_PCP = 'Office visit - PCP',
  OFFICE_VISIT_PCP_AFTER_HOURS = 'Office visit - PCP - After hours',
  OFFICE_VISIT_SPECIALIST = 'Office visit - specialist',
  OFFICE_VISIT_SPECIALIST_AFTER_HOURS = 'Office visit - specialist - After hours',
  OSTEOPOROSIS_DIAGNOSTIC = 'Osteoporosis screening - diagnostic',
  PAIN_MANAGEMENT = 'Pain management',
  PHYSICAL_THERAPY_INPATIENT = 'Physical therapy - inpatient',
  PHYSICAL_THERAPY_OUTPATIENT = 'Physical therapy - outpatient',
  PROSTHETICS = 'Prosthetics',
  RADIATION_THERAPY = 'Radiation therapy',
  RESPIRATORY_EDUCATION = 'Respiratory education',
  SKILLED_NURSING = 'Skilled nursing facility',
  SPEECH_THERAPY_INITIAL = 'Speech therapy - initial evaluation and inpatient',
  SPEECH_THERAPY_OUTPATIENT = 'Speech therapy - outpatient',
  SURGERY = 'Surgery',
  TELEMEDICINE_PCP = 'Telemedicine - PCP',
  TELEMEDICINE_SPECIALIST = 'Telemedicine - specialist',
  TELEMEDICINE_URGENT_CARE = 'Telemedicine - urgent care',
  TMJ_DYSFUNCTION = 'Temporomandibular joint dysfunction',
  TRANSPLANTS = 'Transplants',
  TRANSPORTATION = 'Transportation',
  URGENT_CARE = 'Urgent care',

  // Prescriptions
  PRESCRIPTIONS_TIER_1_30_DAY = '[Prescriptions] Tier 1: Low-cost generics (30-day supply at retail)',
  PRESCRIPTIONS_TIER_1_90_DAY = '[Prescriptions] Tier 1: Low-cost generics (90-day supply at retail)',
  PRESCRIPTIONS_TIER_1_90_DAY_MAIL_ORDER = '[Prescriptions] Tier 1: Low-cost generics (90-day supply at Costco Mail Order)',
  PRESCRIPTIONS_TIER_2_30_DAY = '[Prescriptions] Tier 2: Preferred brands and high-cost generics (30-day supply at retail)',
  PRESCRIPTIONS_TIER_2_90_DAY = '[Prescriptions] Tier 2: Preferred brands and high-cost generics (90-day supply at retail)',
  PRESCRIPTIONS_TIER_2_90_DAY_MAIL_ORDER = '[Prescriptions] Tier 2: Preferred brands and high-cost generics (90-day supply at Costco Mail Order)',
  PRESCRIPTIONS_TIER_3_30_DAY = '[Prescriptions] Tier 3: Non-preferred brands (30-day supply at retail)',
  PRESCRIPTIONS_TIER_3_90_DAY = '[Prescriptions] Tier 3: Non-preferred brands (90-day supply at retail)',
  PRESCRIPTIONS_TIER_3_90_DAY_MAIL_ORDER = '[Prescriptions] Tier 3: Non-preferred brands (90-day supply at Costco Mail Order)',
}

const SERVICES_BY_NAME = Object.values(Service).reduce((acc, serviceName) => {
  acc[serviceName] = serviceName;
  return acc;
}, {} as Record<string, Service>);

export function parseService(serviceName: string): Service {
  return SERVICES_BY_NAME[serviceName];
}